# Generated by Django 4.2 on 2025-07-18 08:23

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_quote',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text/Quote'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=post.models.user_directory_path, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=10000, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
