# Generated by Django 4.2 on 2025-07-18 09:40

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_link_post_location_post_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_video',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
    ]
